### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'stylelint') at updateDependencies

### ISSUE THREAD

**Issue by fcaldera** [Phillip9587/nx-stylelint#490]
`nx g nx-stylelint:init` fails when `package.json` doesn't contains a `dependencies: {}` entry with following error:

```
TypeError: Cannot read properties of undefined (reading 'stylelint')
    at updateDependencies (<project-path>/node_modules/nx-stylelint/src/generators/init/generator.js:30:35)
    at initGenerator (<project-path>/node_modules/nx-stylelint/src/generators/init/generator.js:9:25)
    at Object.<anonymous> (<project-path>/node_modules/nx/src/command-line/generate.js:249:36)
    at Generator.next (<anonymous>)
    at fulfilled (<project-path>/node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```
nx: v16.0.0
nx-stylelint: v15.0.0
```

**Comment by Phillip9587** [comment]
Resolved by ee6e452c05f037c391228e4dc659975aafdccff7
