### ISSUE TITLE
bug: TypeError: The URL must be of scheme file

### ISSUE THREAD

**Issue by muuvmuuv** [Phillip9587/nx-stylelint#593]
In the latest NX release I get this error in my jest tests where I create a component programatically.

```
 FAIL   workspace  libs/workspace/src/generators/new-feature/generator.spec.ts
  ● Test suite failed to run

    TypeError: The URL must be of scheme file

      4 | import * as nx from "@nx/devkit"
      5 | import type { Tree } from "@nx/devkit"
    > 6 | import * as stylelint from "nx-stylelint"
        | ^
      7 |
      8 | import { Schema } from "./schema"
      9 |

      at Object.<anonymous> (../../node_modules/.pnpm/stylelint@16.1.0_typescript@5.2.2/node_modules/stylelint/lib/utils/FileCache.cjs:17:32)
      at Object.<anonymous> (../../node_modules/.pnpm/stylelint@16.1.0_typescript@5.2.2/node_modules/stylelint/lib/createStylelint.cjs:7:19)
      at Object.<anonymous> (../../node_modules/.pnpm/stylelint@16.1.0_typescript@5.2.2/node_modules/stylelint/lib/index.cjs:7:25)
      at Object.<anonymous> (../../node_modules/.pnpm/nx-stylelint@17.1.0_nx@17.2.8_stylelint-config-standard-scss@13.0.0_stylelint-config-standard@36.0.0_stylelint@16.1.0/nx-stylelint/src/utils/formatter.ts:3:1)
      at Object.<anonymous> (../../node_modules/.pnpm/nx-stylelint@17.1.0_nx@17.2.8_stylelint-config-standard-scss@13.0.0_stylelint-config-standard@36.0.0_stylelint@16.1.0/nx-stylelint/src/executors/lint/executor.ts:6:1)
      at Object.<anonymous> (../../node_modules/.pnpm/nx-stylelint@17.1.0_nx@17.2.8_stylelint-config-standard-scss@13.0.0_stylelint-config-standard@36.0.0_stylelint@16.1.0/nx-stylelint/src/index.ts:1:1)
      at Object.<anonymous> (src/generators/new-feature/generator.ts:6:1)
      at Object.<anonymous> (src/generators/new-feature/generator.spec.ts:4:1)
```

Generator code:

```ts
import * as angular from "@nx/angular/generators"
import * as nx from "@nx/devkit"
import type { Tree } from "@nx/devkit"
import * as stylelint from "nx-stylelint"

import { Schema } from "./schema"

export default async function (tree: Tree, schema: Schema) {
  await angular.libraryGenerator(tree, {
    name: "feature-" + schema.name,
    importPath: `@entergon/feature/${schema.name}`,
    projectNameAndRootFormat: "as-provided",
    directory: "libs/feature/" + schema.name,
    prefix: "entergon",
    tags: "feature",
    skipFormat: true,
    changeDetection: "OnPush",
    strict: true,
    style: "scss",
    standalone: true,
  })

  await stylelint.configurationGenerator(tree, {
    formatter: "string",
    project: `feature-${schema.name}`,
    skipFormat: true,
    scss: true,
  })

  for (const project of nx.getProjects(tree)) {
    console.log(project)
  }
  console.log(tree)

  await nx.formatFiles(tree)
}
```

**Comment by Phillip9587** [comment]
@muuvmuuv I don't think your error is related to nx-stylelint. Do you run your tests with a custom setup or standard nx / jest setup?

**Comment by muuvmuuv** [comment]
Standart setup, when I remove the nx-stylelint import it does not appear so it seems like an nx-stylelint issue to me.

**Comment by Phillip9587** [comment]
Is your [testEnvironment](https://jestjs.io/docs/configuration#testenvironment-string) set to node? 

And can you provide the output of `nx report`?

**Comment by muuvmuuv** [comment]
Did not changed it so it must be node since its the default. It is a workspace generator, here the jest config:

```js
export default {
  displayName: "workspace",
  preset: "../../jest.preset.js",
  transform: {
    "^.+\\.[tj]s$": ["ts-jest", { tsconfig: "<rootDir>/tsconfig.spec.json" }],
  },
  moduleFileExtensions: ["ts", "js", "html"],
}
```

Report:

```
   Node   : 20.10.0
   OS     : darwin-arm64
   pnpm   : 8.14.0
   
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/plugin         : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @ionic/angular           : 7.6.3
   @ionic/angular-toolkit   : 10.0.0
   @rx-angular/cdk          : 17.0.0
   @rx-angular/template     : 17.0.1
   @testing-library/angular : 15.1.0
   ngx-extended-pdf-viewer  : 19.0.4
   nx-stylelint             : 17.1.0
   ---------------------------------------
   Local workspace plugins:
         @entergon/capacitor
         @entergon/workspace
         @entergon/builder
```

**Comment by muuvmuuv** [comment]
Ok, alright, NX does not set testEnv to node for workspace on default... Setting it manually works.
